name: gdadc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - alembic==1.15.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - autopep8==2.3.2
      - certifi==2025.1.31
      - click==8.1.8
      - dnspython==2.7.0
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - faker==37.0.0
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - flake8==7.1.2
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - ipdb==0.13.13
      - ipython==9.0.2
      - isort==6.0.1
      - jinja2==3.1.6
      - mako==1.3.9
      - numpy==2.2.3
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pycodestyle==2.12.1
      - pycryptodome==3.21.0
      - pydantic==2.10.6
      - pydantic-settings==2.8.1
      - pyflakes==3.2.0
      - pygments==2.19.1
      - pyodbc==5.2.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - rich==13.9.4
      - shellingham==1.5.4
      - sqlalchemy==2.0.38
      - sqlmodel==0.0.24
      - starlette==0.46.1
      - typer==0.15.2
      - uvicorn==0.34.0
      - uvloop==0.21.0 ; sys_platform != 'win32'
      - watchfiles==1.0.4
      - websockets==15.0.1
